language: android
sudo: required
jdk: oraclejdk8

# Recommended cache configuration from https://docs.travis-ci.com/user/languages/android/
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.android/build-cache

android:
    components:
        # Latest revisions
        - tools
        - platform-tools
        - extra

        # BuildTools and SDK version used by project
        - android-28
        - build-tools-28.0.3

    licenses:
        # Ensure licenses are accepted for latest revisions
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
before_install:
    # Accept licenses for android-28 as per https://stackoverflow.com/a/52954536/4896787
    - yes | sdkmanager "platforms;android-28"

script:
    # Ensure kotlin passes lint check
    - ./gradlew ktlint
    # Ensure the app builds
    - ./gradlew assemble
    # Unit tests
    - ./gradlew test
